### ISSUE TITLE
Output Files Not Created In Latest Version

### ISSUE THREAD

**Issue by Miserlou** [COMBINE-lab/SalmonTools#3]
The same wrapper code running with `474ba5947711074a015a268b47058ac8930cf566` and the current `master` HEAD creates different behavior.

With `474ba5947711074a015a268b47058ac8930cf566`, there are files at the expected location with the command:

`
salmontools extract-unmapped -u /home/user/data_store/salmontools/double_output/aux_info/unmapped_names.txt -o /home/user/data_store/salmontools/double_salmontools/unmapped_by_salmon -1 /home/user/data_store/salmontools/double_input/reads_1.fastq -2 /home/user/data_store/salmontools/double_input/reads_2.fastq
`

When using master, the output files don't exist at the location. It simply says, `There were 100 unmapped reads`, but no new files appear.

Any ideas?

**Comment by hiraksarkar** [comment]
Hi @Miserlou , 
Thanks for reporting the error. Trying to debug it. 
Is this happening just for this set of reads, or for all the samples?

**Comment by Miserlou** [comment]
The example is for our CI test case, which tests both single and double, both fail.

**Comment by hiraksarkar** [comment]
Hi @Miserlou, 

Can you please confirm if the `/home/user/data_store/salmontools/double_salmontools/` folder existed before running or not ?

**Comment by hiraksarkar** [comment]
#4 This pull req will create the output directory if not exists and might be the issue for above behavior. Requesting @rob-p to merge.

**Comment by hiraksarkar** [comment]
@Miserlou , 
Was wondering if the problem is solved.

**Comment by Miserlou** [comment]
Yep! That got it. Sorry for the delayed reply, and thank you for your swift response!
